import type { ReviewProvider } from '../providers/provider.js';
import type {
  ReviewTarget,
  ReviewTargetRef,
  WorkspaceBundle,
  BundleState,
  BundleLocal,
  NewFinding,
  PrepareSummary,
  RemoteCheckpoint,
  BundleComparison,
} from '../core/types.js';
import type { ResolvedAppConfig } from '../config/types.js';
import { WorkspaceManager } from '../workspace/workspace-manager.js';
import { GitHelper } from '../workspace/git-helper.js';
import {
  computeAggregateThreadsDigest,
  computeContentHash,
  computeThreadDigest,
  computeThreadDigestMap,
} from '../workspace/thread-digest.js';
import { activeReviewThreads, filterReviewThreads } from '../workspace/thread-utils.js';
import { extractMarkedSummary } from '../workspace/description-summary.js';
import {
  parseCheckpointMarker,
  buildCheckpointState,
  buildReviewNoteBody,
  updateReviewNoteBody,
  REVIEW_NOTE_MARKER,
  stripReviewNoteFooter,
} from '../workspace/checkpoint.js';

export interface OrchestratorOptions {
  provider: ReviewProvider;
  workingDir: string;
  runtimeConfig?: ResolvedAppConfig;
}

export interface PrepareResult {
  bundle: WorkspaceBundle;
  bundleState: BundleState;
  contextPath: string;
  mode: 'fresh' | 'refresh' | 'target_changed';
  targetCodeChanged: boolean | null;
  threadsChanged: boolean | null;
  descriptionChanged: boolean | null;
  hasCheckpoint: boolean;
  prunedReplies: number;
  publishedActionCount: number;
}

export interface CheckoutResult {
  branch: string;
  target: ReviewTarget;
  clonedTo?: string;
}

/**
 * Central orchestrator that coordinates provider and workspace into coherent review workflows.
 */
export class ReviewOrchestrator {
  private readonly provider: ReviewProvider;
  readonly workspace: WorkspaceManager;
  private readonly git: GitHelper;
  // private readonly runtimeConfig?: ResolvedAppConfig;

  static readonly COMMENT_MARKER = '<!-- revkit -->';
  static readonly AI_FOOTER = '\n\n<sub>🤖 Generated by revkit</sub>';

  constructor(options: OrchestratorOptions) {
    this.provider = options.provider;
    this.workspace = new WorkspaceManager(options.workingDir);
    this.git = new GitHelper(options.workingDir);
    // this.runtimeConfig = options.runtimeConfig;
  }

  // ─── High-level workflows ──────────────────────────────

  /**
   * Prepare: the primary workflow.
   * Fetches MR data, generates/refreshes the .revkit/ bundle.
   * Does NOT perform a review or create findings.
   */
  async prepare(
    ref?: string,
    defaultRepo?: string,
    options?: { fresh?: boolean; discardOutputs?: boolean },
  ): Promise<PrepareResult> {
    const existingBundle = await this.workspace.loadBundleState();

    // --fresh: remove everything and start clean
    if (options?.fresh) {
      await this.workspace.removeBundle();
    }

    // Discard outputs if requested
    if (options?.discardOutputs) {
      await this.workspace.discardOutputs();
    }

    const targetRef = await this.resolveRef(ref, defaultRepo);

    // Determine prepare mode
    let mode: PrepareSummary['mode'] = 'fresh';
    const previousBundle = options?.fresh ? null : existingBundle;
    if (previousBundle) {
      if (previousBundle.target.id !== targetRef.targetId) {
        mode = 'target_changed';
      } else {
        mode = 'refresh';
      }
    }

    // Fetch all data in parallel
    const [target, rawThreads, diffs, versions] = await Promise.all([
      this.provider.getTargetSnapshot(targetRef),
      this.provider.listAllThreads(targetRef),
      this.provider.getLatestDiff(targetRef),
      this.provider.getDiffVersions(targetRef),
    ]);

    // ─── Fetch remote checkpoint from managed review note ──
    let remoteCheckpoint: RemoteCheckpoint | null = null;
    let checkpointNoteId: string | null = null;
    let reviewNoteVisibleContent: string | null = null;

    let reviewNote: { id: string; body: string } | null = null;
    try {
      reviewNote = await this.provider.findNoteByMarker(targetRef, REVIEW_NOTE_MARKER);
    } catch {
      // Provider lookup failed — treat as no checkpoint
    }

    if (reviewNote) {
      checkpointNoteId = reviewNote.id;
      try {
        const parsed = parseCheckpointMarker(reviewNote.body);
        if (parsed) {
          reviewNoteVisibleContent = parsed.visibleContent || null;
          remoteCheckpoint = {
            source: 'managed_review_note',
            providerNoteId: checkpointNoteId,
            headSha: parsed.state.checkpoint.headSha,
            baseSha: parsed.state.checkpoint.baseSha,
            startSha: parsed.state.checkpoint.startSha,
            providerVersionId: parsed.state.checkpoint.providerVersionId,
            threadsDigest: parsed.state.checkpoint.threadsDigest,
            descriptionDigest: parsed.state.checkpoint.descriptionDigest ?? null,
            threadDigests: parsed.state.checkpoint.threadDigests ?? {},
            createdAt: parsed.state.checkpoint.createdAt,
          };
        }
      } catch {
        // Malformed checkpoint — treat as no checkpoint
      }
    }

    // ─── Source consistency check ─────────────────────────
    // Must verify local checkout matches MR/PR head BEFORE writing anything.
    const mrHeadSha = target.diffRefs.headSha;
    let localHeadSha: string;
    let localBranch: string;
    let localRepoRoot: string;
    let localClean: boolean;

    try {
      [localHeadSha, localBranch, localRepoRoot, localClean] = await Promise.all([
        this.git.headSha(),
        this.git.currentBranch(),
        this.git.repositoryRoot(),
        this.git.isClean(),
      ]);
    } catch {
      throw new Error(
        'Cannot prepare: not inside a git repository.\n' +
          'Run `revkit checkout` first to clone or switch to the MR source branch.',
      );
    }

    // Check branch matches MR source branch
    if (localBranch !== 'HEAD' && localBranch !== target.sourceBranch) {
      throw new Error(
        `Cannot prepare because the current branch does not match the MR source branch.\n\n` +
          `MR source branch: ${target.sourceBranch}\n` +
          `Current branch:   ${localBranch}\n\n` +
          `Run:\n\n` +
          `  revkit checkout !${target.targetId}\n` +
          `  revkit prepare`,
      );
    }

    // Check local HEAD matches MR/PR head
    if (localHeadSha !== mrHeadSha) {
      const isAncestor = await this.git.isAncestor(mrHeadSha).catch(() => false);
      if (isAncestor) {
        // Local is ahead of MR head
        throw new Error(
          `Cannot prepare an agent-ready bundle because the local checkout is ahead of the MR head.\n\n` +
            `MR head:     ${mrHeadSha}\n` +
            `Local HEAD:  ${localHeadSha}\n\n` +
            `Push your commits or reset/switch to the MR head, then run:\n\n` +
            `  revkit prepare`,
        );
      } else {
        // Local is behind MR head
        throw new Error(
          `Cannot prepare an agent-ready bundle because the local checkout is behind the MR head.\n\n` +
            `MR head:     ${mrHeadSha}\n` +
            `Local HEAD:  ${localHeadSha}\n\n` +
            `Run:\n\n` +
            `  git pull\n` +
            `  revkit prepare`,
        );
      }
    }

    // ─── Source consistency verified — proceed with writes ─

    // Filter out system-only threads and the managed review note thread
    const reviewNoteCommentId = checkpointNoteId;
    const allThreads = filterReviewThreads(rawThreads, reviewNoteCommentId);

    // Build position-based thread index
    const threadIndex = WorkspaceManager.buildThreadIndex(allThreads);

    // Only non-resolved threads go into the bundle
    const activeThreads = activeReviewThreads(allThreads);

    // Create the bundle
    const bundle = await this.workspace.createBundle(target, activeThreads, diffs, versions, threadIndex);

    // Compute prepare summary — compare against remote checkpoint
    const latestVersionId = versions.length > 0 ? versions[0].versionId : undefined;
    const currentThreadsDigest = computeAggregateThreadsDigest(allThreads);
    const currentDescriptionDigest = computeContentHash(target.description ?? '');

    // Compare against checkpoint (not previous local prepare)
    const targetCodeChanged = remoteCheckpoint ? remoteCheckpoint.headSha !== mrHeadSha : null;

    const threadsChanged = remoteCheckpoint?.threadsDigest
      ? remoteCheckpoint.threadsDigest !== currentThreadsDigest
      : null;

    const descriptionChanged = remoteCheckpoint?.descriptionDigest
      ? remoteCheckpoint.descriptionDigest !== currentDescriptionDigest
      : null;

    const comparison: BundleComparison = {
      targetCodeChangedSinceCheckpoint: targetCodeChanged,
      threadsChangedSinceCheckpoint: threadsChanged,
      descriptionChangedSinceCheckpoint: descriptionChanged,
    };

    const prepareSummary: PrepareSummary = {
      mode,
      checkpoint: remoteCheckpoint,
      current: {
        providerVersionId: latestVersionId,
        targetHeadSha: mrHeadSha,
        localHeadSha,
        threadsDigest: currentThreadsDigest,
        descriptionDigest: currentDescriptionDigest,
      },
      comparison,
    };

    // Build local metadata
    const localMetadata: BundleLocal = {
      repositoryRoot: localRepoRoot,
      branch: localBranch,
      headSha: localHeadSha,
      matchesTargetSourceBranch: localBranch === target.sourceBranch,
      matchesTargetHead: localHeadSha === mrHeadSha,
      workingTreeClean: localClean,
      checkedAt: new Date().toISOString(),
    };

    // Incremental diff relative to checkpoint head (not previous prepare)
    if (targetCodeChanged && remoteCheckpoint) {
      // Prefer git-based diff: `git diff fromSha toSha` gives the true incremental
      // changes between two commits, unlike the provider API which returns full
      // file diffs against the target branch for files that changed between versions.
      try {
        await this.workspace.writeIncrementalDiffFromGit(this.git, remoteCheckpoint.headSha, mrHeadSha);
      } catch {
        // Fall back to provider-based incremental diff if git is unavailable
        if (remoteCheckpoint.providerVersionId && latestVersionId) {
          try {
            const incrementalDiffs = await this.provider.getIncrementalDiff(
              targetRef,
              remoteCheckpoint.providerVersionId,
              latestVersionId,
            );
            await this.workspace.writeIncrementalDiff(incrementalDiffs);
          } catch {
            // No incremental patch available
          }
        }
      }
    } else if (remoteCheckpoint && !targetCodeChanged) {
      await this.workspace.writeNoCodeChangeIncrementalPatch();
    }

    // Prune stale replies
    let prunedReplies = 0;
    if (previousBundle) {
      const activeIds = new Set(activeThreads.map((t) => t.threadId));
      prunedReplies = await this.workspace.pruneStaleReplies(activeIds, threadIndex);
    }

    // Carry over published actions and output state from previous bundle
    const previousActions = previousBundle && mode !== 'fresh' ? previousBundle.publishedActions : [];
    const previousOutputs = previousBundle && mode !== 'fresh' ? previousBundle.outputs : undefined;

    // Compute per-thread changes since the last checkpoint.
    // The checkpoint baseline (per-thread digests at the time of the last publish) is
    // stable across multiple prepares, so "Changed Threads" persists until a new
    // checkpoint is published.
    let changedThreadIds: Set<string> | undefined;

    // Resolve checkpoint baseline: carried-forward local > remote checkpoint > fresh snapshot
    const checkpointChanged =
      previousBundle && remoteCheckpoint && previousBundle.prepare.checkpoint?.headSha !== remoteCheckpoint.headSha;

    const checkpointDigests: Record<string, string> =
      previousBundle && !checkpointChanged
        ? previousBundle.threads.checkpointDigests
        : (remoteCheckpoint?.threadDigests ?? computeThreadDigestMap(allThreads));

    if (threadsChanged) {
      changedThreadIds = new Set<string>();
      for (const t of allThreads) {
        const currentDigest = computeThreadDigest(t);
        const baseDigest = checkpointDigests[t.threadId];
        if (!baseDigest || baseDigest !== currentDigest) {
          changedThreadIds.add(t.threadId);
        }
      }
    }

    // Write CONTEXT.md
    const contextPath = await this.workspace.writeContext(target, activeThreads, diffs, threadIndex, {
      prepareSummary,
      publishedActions: previousActions,
      changedThreadIds,
      allThreads,
    });

    // Build and save bundle.json
    const bundleState = this.workspace.buildBundleState(
      target,
      allThreads,
      versions,
      threadIndex,
      prepareSummary,
      localMetadata,
      previousActions,
      previousOutputs,
      activeThreads,
      checkpointDigests,
    );
    await this.workspace.saveBundleState(bundleState);

    // Prefill outputs from the last published remote content
    // so agents can see and update existing content in incremental mode.
    // Must happen AFTER saveBundleState so the hash update persists.
    const publishedSummary = extractMarkedSummary(target.description ?? '');
    if (publishedSummary) {
      await this.workspace.prefillOutputIfEmpty('summary.md', publishedSummary);
    }
    if (reviewNoteVisibleContent && remoteCheckpoint) {
      await this.workspace.prefillOutputIfEmpty('review.md', stripReviewNoteFooter(reviewNoteVisibleContent));
    }

    return {
      bundle,
      bundleState,
      contextPath,
      mode,
      targetCodeChanged,
      threadsChanged,
      descriptionChanged,
      hasCheckpoint: remoteCheckpoint !== null,
      prunedReplies,
      publishedActionCount: previousActions.length,
    };
  }

  /**
   * Open: resolve ref, fetch snapshot.
   */
  async open(ref?: string, defaultRepo?: string): Promise<ReviewTarget> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    return this.provider.getTargetSnapshot(targetRef);
  }

  /**
   * Check if the current git branch matches the active bundle's target.
   * Returns null if no bundle or no git info available.
   */
  async checkBranchMismatch(): Promise<{ currentBranch: string; expectedBranch: string; targetId: string } | null> {
    const bundleState = await this.workspace.loadBundleState();
    if (!bundleState) return null;
    try {
      const currentBranch = await this.git.currentBranch();
      if (!currentBranch || currentBranch === 'HEAD') return null;
      if (currentBranch !== bundleState.target.sourceBranch) {
        return {
          currentBranch,
          expectedBranch: bundleState.target.sourceBranch,
          targetId: bundleState.target.id,
        };
      }
    } catch {
      // Can't check — not a git repo or API error
    }
    return null;
  }

  /**
   * Checkout: fetch the MR source branch and switch to it.
   * If we're not inside a git repo, performs a shallow clone instead.
   */
  async checkout(ref: string, defaultRepo?: string): Promise<CheckoutResult> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    const target = await this.provider.getTargetSnapshot(targetRef);

    const inRepo = await this.git.isGitRepo();

    if (!inRepo) {
      // No git repo — shallow clone into a sub-directory, similar to `git clone`
      const cloneUrl = this.provider.getCloneUrl(targetRef.repository);
      const clonedDir = await GitHelper.clone(cloneUrl, target.sourceBranch, this.git.cwd);
      return { branch: target.sourceBranch, target, clonedTo: clonedDir };
    }

    // Existing repo — fetch the MR source branch first.
    await this.git.fetchBranch(target.sourceBranch);

    try {
      // Let Git decide whether switching is safe.
      //
      // This allows harmless local state, such as unrelated untracked files,
      // while still refusing switches that would overwrite local changes.
      await this.git.switchBranch(target.sourceBranch);
    } catch (error) {
      throw new Error(
        [
          `Could not switch to branch '${target.sourceBranch}'.`,
          '',
          'Git refused the switch because it would overwrite local changes or otherwise could not safely update the working tree.',
          'Commit, stash, move, or remove the conflicting files, then try again.',
          '',
          `Original error: ${error instanceof Error ? error.message : String(error)}`,
        ].join('\n'),
        { cause: error },
      );
    }

    return { branch: target.sourceBranch, target };
  }

  // ─── Write operations (guarded) ─────────────────────────

  async publishReply(ref?: string, threadId?: string, body?: string, defaultRepo?: string): Promise<void> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    if (!threadId) throw new Error('threadId is required');
    if (!body) throw new Error('reply body is required');
    const resolvedId = await this.workspace.resolveThreadRef(threadId);
    const markedBody = `${ReviewOrchestrator.COMMENT_MARKER}\n${body}${ReviewOrchestrator.AI_FOOTER}`;
    await this.provider.postReply(targetRef, resolvedId, markedBody);
  }

  async resolveThread(ref?: string, threadId?: string, defaultRepo?: string): Promise<void> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    if (!threadId) throw new Error('threadId is required');
    const resolvedId = await this.workspace.resolveThreadRef(threadId);
    await this.provider.resolveThread(targetRef, resolvedId);
  }

  async updateDescription(ref?: string, body?: string, defaultRepo?: string): Promise<void> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    if (!body) throw new Error('description body is required');
    await this.provider.updateDescription(targetRef, body);
  }

  /**
   * Publish a new finding as a discussion thread on the MR/PR.
   * Returns the created thread ID.
   */
  async publishFinding(finding: NewFinding, defaultRepo?: string): Promise<string> {
    const targetRef = await this.resolveRef(undefined, defaultRepo);
    const markedBody = `${ReviewOrchestrator.COMMENT_MARKER}\n${finding.body}${ReviewOrchestrator.AI_FOOTER}`;
    return this.provider.createThread(targetRef, markedBody, {
      oldPath: finding.oldPath,
      newPath: finding.newPath,
      newLine: finding.newLine,
      oldLine: finding.oldLine,
    });
  }

  /** Resolve a T-NNN shorthand to the full thread SHA. */
  async resolveThreadRef(ref: string): Promise<string> {
    return this.workspace.resolveThreadRef(ref);
  }

  /** Review note marker for finding/updating the managed review note. */
  static readonly REVIEW_COMMENT_MARKER = REVIEW_NOTE_MARKER;

  /**
   * Publish review: create or update the managed review note and advance the checkpoint.
   *
   * - If visibleContent is non-empty, uses it as the visible note body.
   * - If visibleContent is empty and a managed note exists, preserves existing visible content.
   * - If visibleContent is empty and no managed note exists, creates a minimal visible note.
   * - Always updates the hidden checkpoint marker.
   */
  async publishReview(visibleContent: string, defaultRepo?: string): Promise<{ created: boolean; noteId?: string }> {
    const targetRef = await this.resolveRef(undefined, defaultRepo);
    const marker = REVIEW_NOTE_MARKER;

    // Fetch current state for the checkpoint (include existing note lookup for consistent filtering)
    const [target, rawThreads, existingNote] = await Promise.all([
      this.provider.getTargetSnapshot(targetRef),
      this.provider.listAllThreads(targetRef),
      this.provider.findNoteByMarker(targetRef, marker).catch(() => null),
    ]);

    // Exclude system-only threads AND the review note's own thread
    // (must match the filtering in prepare() to produce consistent digests)
    const reviewNoteId = existingNote?.id ?? null;
    const allThreads = filterReviewThreads(rawThreads, reviewNoteId);
    const currentThreadsDigest = computeAggregateThreadsDigest(allThreads);
    const currentDescriptionDigest = computeContentHash(target.description ?? '');
    const threadDigests = computeThreadDigestMap(allThreads);

    const versions = await this.provider.getDiffVersions(targetRef);
    const latestVersionId = versions.length > 0 ? versions[0].versionId : undefined;

    // Build the new checkpoint state
    const checkpointState = buildCheckpointState(
      targetRef,
      target.diffRefs.headSha,
      target.diffRefs.baseSha,
      target.diffRefs.startSha,
      currentThreadsDigest,
      latestVersionId,
      currentDescriptionDigest,
      threadDigests,
    );

    if (existingNote) {
      // Update existing managed note
      let fullBody: string;

      if (visibleContent.trim()) {
        fullBody = buildReviewNoteBody(visibleContent, checkpointState);
      } else {
        fullBody = updateReviewNoteBody(existingNote.body, checkpointState);
      }

      await this.provider.updateNote(targetRef, existingNote.id, fullBody);
      return { created: false, noteId: existingNote.id };
    } else {
      // Create new managed note
      const content = visibleContent.trim() ? visibleContent : 'Reviewed current changes. No additional review notes.';
      const fullBody = buildReviewNoteBody(content, checkpointState);
      const noteId = await this.provider.createNote(targetRef, fullBody, { internal: true });
      return { created: true, noteId };
    }
  }

  // ─── Helpers ────────────────────────────────────────────

  private async resolveRef(ref?: string, defaultRepo?: string): Promise<ReviewTargetRef> {
    // 1. Explicit ref
    if (ref) {
      const targetRef = this.provider.resolveTarget(ref);
      if (!targetRef.repository && defaultRepo) {
        targetRef.repository = defaultRepo;
      }
      if (!targetRef.repository) {
        targetRef.repository = await this.git.deriveRepoSlug();
      }
      return targetRef;
    }

    // 2. Existing bundle.json
    const bundleState = await this.workspace.loadBundleState();
    if (bundleState) {
      // If we can determine the current branch, check it matches
      try {
        const currentBranch = await this.git.currentBranch();
        if (currentBranch && currentBranch !== 'HEAD' && currentBranch !== bundleState.target.sourceBranch) {
          throw new Error(
            `Branch mismatch: current branch "${currentBranch}" does not match ` +
              `the bundle's MR source branch "${bundleState.target.sourceBranch}" (!${bundleState.target.id}).\n` +
              `Run \`revkit clean\` to remove the stale bundle, or switch to "${bundleState.target.sourceBranch}".`,
          );
        }
      } catch (err) {
        if (err instanceof Error && err.message.includes('Branch mismatch')) throw err;
      }
      return {
        provider: bundleState.target.provider,
        repository: bundleState.target.repository,
        targetType: bundleState.target.type,
        targetId: bundleState.target.id,
      };
    }

    // 3. Auto-detect MR from current git branch
    let repo = defaultRepo;
    if (!repo) {
      try {
        repo = await this.git.deriveRepoSlug();
      } catch {
        /* not a git repo */
      }
    }
    if (repo) {
      try {
        const branch = await this.git.currentBranch();
        if (branch && branch !== 'HEAD') {
          const targets = await this.provider.findTargetByBranch(repo, branch);
          if (targets.length === 1) {
            return targets[0];
          }
          if (targets.length > 1) {
            const ids = targets.map((t) => `!${t.targetId}`).join(', ');
            throw new Error(
              `Multiple open MRs found for branch "${branch}": ${ids}\n` +
                'Specify one explicitly: `revkit prepare !<id>`',
            );
          }
        }
      } catch (err) {
        if (err instanceof Error && err.message.includes('Multiple open MRs')) throw err;
      }
    }

    throw new Error(
      'Could not determine which MR to prepare.\n' +
        'No ref provided, no existing bundle, and no open MR found for the current branch.\n' +
        'Run `revkit prepare !<id>` to specify one explicitly.',
    );
  }
}
