import type { ReviewProvider } from '../providers/provider.js';
import type {
  ReviewTarget,
  ReviewTargetRef,
  ReviewDiff,
  WorkspaceBundle,
  BundleState,
  BundleLocal,
  NewFinding,
  PrepareSummary,
  RemoteCheckpoint,
  BundleComparison,
} from '../core/types.js';
import type { ResolvedAppConfig } from '../config/types.js';
import { WorkspaceManager } from '../workspace/workspace-manager.js';
import { GitHelper } from '../workspace/git-helper.js';
import { parsePatch } from '../workspace/patch-parser.js';
import {
  computeAggregateThreadsDigest,
  computeContentHash,
  computeThreadDigest,
  computeThreadDigestMap,
} from '../workspace/thread-digest.js';
import { activeReviewThreads, filterReviewThreads } from '../workspace/thread-utils.js';
import { extractMarkedSummary } from '../workspace/description-summary.js';
import {
  buildCheckpointState,
  parseDescriptionState,
  patchDescriptionWithState,
  sanitizeDescriptionForAgent,
  REVIEW_NOTE_MARKER,
  REVIEW_NOTE_FOOTER,
} from '../workspace/checkpoint.js';

export interface OrchestratorOptions {
  provider: ReviewProvider;
  workingDir: string;
  runtimeConfig?: ResolvedAppConfig;
}

export interface PrepareResult {
  bundle: WorkspaceBundle;
  bundleState: BundleState;
  contextPath: string;
  mode: 'fresh' | 'refresh' | 'target_changed';
  targetCodeChanged: boolean | null;
  threadsChanged: boolean | null;
  descriptionChanged: boolean | null;
  hasCheckpoint: boolean;
  prunedReplies: number;
  publishedActionCount: number;
  diffFallback?: PrepareDiffFallback;
}

export interface PrepareDiffFallback {
  provider: 'gitlab';
  reason: string;
  incompleteFileCount: number;
  baseSha: string;
  headSha: string;
}

interface LocalPatchFallbackResult extends PrepareDiffFallback {
  patchContent: string;
}

export interface CheckoutResult {
  branch: string;
  target: ReviewTarget;
  clonedTo?: string;
}

/**
 * Central orchestrator that coordinates provider and workspace into coherent review workflows.
 */
export class ReviewOrchestrator {
  private readonly provider: ReviewProvider;
  readonly workspace: WorkspaceManager;
  private readonly git: GitHelper;
  // private readonly runtimeConfig?: ResolvedAppConfig;

  static readonly COMMENT_MARKER = '<!-- revkit -->';
  static readonly AI_FOOTER = '\n\n<sub>🤖 Generated by revkit</sub>';

  constructor(options: OrchestratorOptions) {
    this.provider = options.provider;
    this.workspace = new WorkspaceManager(options.workingDir);
    this.git = new GitHelper(options.workingDir);
    // this.runtimeConfig = options.runtimeConfig;
  }

  // ─── High-level workflows ──────────────────────────────

  /**
   * Prepare: the primary workflow.
   * Fetches MR data, generates/refreshes the .revkit/ bundle.
   * Does NOT perform a review or create findings.
   */
  async prepare(
    ref?: string,
    defaultRepo?: string,
    options?: { fresh?: boolean; discardOutputs?: boolean },
  ): Promise<PrepareResult> {
    const existingBundle = await this.workspace.loadBundleState();

    // --fresh: remove everything and start clean
    if (options?.fresh) {
      await this.workspace.removeBundle();
    }

    // Discard outputs if requested
    if (options?.discardOutputs) {
      await this.workspace.discardOutputs();
    }

    const targetRef = await this.resolveRef(ref, defaultRepo);

    // Determine prepare mode
    let mode: PrepareSummary['mode'] = 'fresh';
    const previousBundle = options?.fresh ? null : existingBundle;
    if (previousBundle) {
      if (previousBundle.target.id !== targetRef.targetId) {
        mode = 'target_changed';
      } else {
        mode = 'refresh';
      }
    }

    // Fetch all data in parallel
    const [target, rawThreads, diffs, versions] = await Promise.all([
      this.provider.getTargetSnapshot(targetRef),
      this.provider.listAllThreads(targetRef),
      this.provider.getLatestDiff(targetRef),
      this.provider.getDiffVersions(targetRef),
    ]);

    // ─── Fetch remote checkpoint from MR/PR description body ──
    let remoteCheckpoint: RemoteCheckpoint | null = null;

    try {
      const descState = parseDescriptionState(target.description ?? '');
      if (descState) {
        remoteCheckpoint = {
          source: 'description_body',
          providerNoteId: '',
          headSha: descState.checkpoint.headSha,
          baseSha: descState.checkpoint.baseSha,
          startSha: descState.checkpoint.startSha,
          providerVersionId: descState.checkpoint.providerVersionId,
          threadsDigest: descState.checkpoint.threadsDigest,
          descriptionDigest: descState.checkpoint.descriptionDigest ?? null,
          threadDigests: descState.checkpoint.threadDigests ?? {},
          createdAt: descState.checkpoint.createdAt,
        };
      }
    } catch (err) {
      // parseDescriptionState throws on duplicate blocks — surface to user
      if (err instanceof Error && err.message.includes('multiple revkit state blocks')) {
        throw err;
      }
      // Malformed state — treat as no checkpoint
    }

    // Identify body-only revkit review notes for exclusion from bundle context
    let reviewNoteCommentId: string | null = null;
    let reviewNote: { id: string; body: string } | null = null;
    try {
      reviewNote = await this.provider.findNoteByMarker(targetRef, REVIEW_NOTE_MARKER);
    } catch {
      // Provider lookup failed
    }
    if (reviewNote) {
      reviewNoteCommentId = reviewNote.id;
    }

    // ─── Source consistency check ─────────────────────────
    // Must verify local checkout matches MR/PR head BEFORE writing anything.
    const mrHeadSha = target.diffRefs.headSha;
    let localHeadSha: string;
    let localBranch: string;
    let localRepoRoot: string;
    let localClean: boolean;

    try {
      [localHeadSha, localBranch, localRepoRoot, localClean] = await Promise.all([
        this.git.headSha(),
        this.git.currentBranch(),
        this.git.repositoryRoot(),
        this.git.isClean(),
      ]);
    } catch {
      throw new Error(
        'Cannot prepare: not inside a git repository.\n' +
          'Run `revkit checkout` first to clone or switch to the MR source branch.',
      );
    }

    // Check branch matches MR source branch
    if (localBranch !== 'HEAD' && localBranch !== target.sourceBranch) {
      throw new Error(
        `Cannot prepare because the current branch does not match the MR source branch.\n\n` +
          `MR source branch: ${target.sourceBranch}\n` +
          `Current branch:   ${localBranch}\n\n` +
          `Run:\n\n` +
          `  revkit checkout !${target.targetId}\n` +
          `  revkit prepare`,
      );
    }

    // Check local HEAD matches MR/PR head
    if (localHeadSha !== mrHeadSha) {
      const isAncestor = await this.git.isAncestor(mrHeadSha).catch(() => false);
      if (isAncestor) {
        // Local is ahead of MR head
        throw new Error(
          `Cannot prepare an agent-ready bundle because the local checkout is ahead of the MR head.\n\n` +
            `MR head:     ${mrHeadSha}\n` +
            `Local HEAD:  ${localHeadSha}\n\n` +
            `Push your commits or reset/switch to the MR head, then run:\n\n` +
            `  revkit prepare`,
        );
      } else {
        // Local is behind MR head
        throw new Error(
          `Cannot prepare an agent-ready bundle because the local checkout is behind the MR head.\n\n` +
            `MR head:     ${mrHeadSha}\n` +
            `Local HEAD:  ${localHeadSha}\n\n` +
            `Run:\n\n` +
            `  git pull\n` +
            `  revkit prepare`,
        );
      }
    }

    // ─── Source consistency verified — proceed with writes ─

    // Filter out system-only threads and the managed review note thread
    const allThreads = filterReviewThreads(rawThreads, reviewNoteCommentId);

    // Build position-based thread index
    const threadIndex = WorkspaceManager.buildThreadIndex(allThreads);

    // Only non-resolved threads go into the bundle
    const activeThreads = activeReviewThreads(allThreads);

    const diffFallback = await this.maybeRegenerateGitLabPatch(target, diffs);
    const bundleDiffs = diffFallback ? this.reviewDiffsFromPatch(diffFallback.patchContent) : diffs;

    // Create the bundle
    const bundle = await this.workspace.createBundle(target, activeThreads, bundleDiffs, versions, threadIndex, {
      latestPatchContent: diffFallback?.patchContent,
    });

    // Compute prepare summary — compare against remote checkpoint
    const latestVersionId = versions.length > 0 ? versions[0].versionId : undefined;
    const currentThreadsDigest = computeAggregateThreadsDigest(allThreads);
    const currentDescriptionDigest = computeContentHash(sanitizeDescriptionForAgent(target.description ?? ''));

    // Compare against checkpoint (not previous local prepare)
    const targetCodeChanged = remoteCheckpoint ? remoteCheckpoint.headSha !== mrHeadSha : null;

    const threadsChanged = remoteCheckpoint?.threadsDigest
      ? remoteCheckpoint.threadsDigest !== currentThreadsDigest
      : null;

    const descriptionChanged = remoteCheckpoint?.descriptionDigest
      ? remoteCheckpoint.descriptionDigest !== currentDescriptionDigest
      : null;

    const comparison: BundleComparison = {
      targetCodeChangedSinceCheckpoint: targetCodeChanged,
      threadsChangedSinceCheckpoint: threadsChanged,
      descriptionChangedSinceCheckpoint: descriptionChanged,
    };

    const prepareSummary: PrepareSummary = {
      mode,
      checkpoint: remoteCheckpoint,
      current: {
        providerVersionId: latestVersionId,
        targetHeadSha: mrHeadSha,
        localHeadSha,
        threadsDigest: currentThreadsDigest,
        descriptionDigest: currentDescriptionDigest,
      },
      comparison,
    };

    // Build local metadata
    const localMetadata: BundleLocal = {
      repositoryRoot: localRepoRoot,
      branch: localBranch,
      headSha: localHeadSha,
      matchesTargetSourceBranch: localBranch === target.sourceBranch,
      matchesTargetHead: localHeadSha === mrHeadSha,
      workingTreeClean: localClean,
      checkedAt: new Date().toISOString(),
    };

    // Incremental diff relative to checkpoint head (not previous prepare)
    if (targetCodeChanged && remoteCheckpoint) {
      // Prefer git-based diff: `git diff fromSha toSha` gives the true incremental
      // changes between two commits, unlike the provider API which returns full
      // file diffs against the target branch for files that changed between versions.
      try {
        await this.workspace.writeIncrementalDiffFromGit(this.git, remoteCheckpoint.headSha, mrHeadSha);
      } catch {
        // Fall back to provider-based incremental diff if git is unavailable
        if (remoteCheckpoint.providerVersionId && latestVersionId) {
          try {
            const incrementalDiffs = await this.provider.getIncrementalDiff(
              targetRef,
              remoteCheckpoint.providerVersionId,
              latestVersionId,
            );
            await this.workspace.writeIncrementalDiff(incrementalDiffs);
          } catch {
            // No incremental patch available
          }
        }
      }
    } else if (remoteCheckpoint && !targetCodeChanged) {
      await this.workspace.writeNoCodeChangeIncrementalPatch();
    }

    // Prune stale replies
    let prunedReplies = 0;
    if (previousBundle) {
      const activeIds = new Set(activeThreads.map((t) => t.threadId));
      prunedReplies = await this.workspace.pruneStaleReplies(activeIds, threadIndex);
    }

    // Carry over published actions and output state from previous bundle
    const previousActions = previousBundle && mode !== 'fresh' ? previousBundle.publishedActions : [];
    const previousOutputs = previousBundle && mode !== 'fresh' ? previousBundle.outputs : undefined;

    // Compute per-thread changes since the last checkpoint.
    // The baseline comes directly from the remote checkpoint's per-thread digests.
    // If no checkpoint exists, we snapshot the current state (no changes detectable).
    let changedThreadIds: Set<string> | undefined;

    const checkpointDigests: Record<string, string> =
      remoteCheckpoint && Object.keys(remoteCheckpoint.threadDigests).length > 0
        ? remoteCheckpoint.threadDigests
        : computeThreadDigestMap(allThreads);

    if (threadsChanged) {
      changedThreadIds = new Set<string>();
      for (const t of allThreads) {
        const currentDigest = computeThreadDigest(t);
        const baseDigest = checkpointDigests[t.threadId];
        if (!baseDigest || baseDigest !== currentDigest) {
          changedThreadIds.add(t.threadId);
        }
      }
    }

    // Write CONTEXT.md
    const contextPath = await this.workspace.writeContext(target, activeThreads, bundleDiffs, threadIndex, {
      prepareSummary,
      publishedActions: previousActions,
      changedThreadIds,
      allThreads,
    });

    // Build and save bundle.json
    const bundleState = this.workspace.buildBundleState(
      target,
      allThreads,
      versions,
      threadIndex,
      prepareSummary,
      localMetadata,
      previousActions,
      previousOutputs,
      activeThreads,
    );
    await this.workspace.saveBundleState(bundleState);

    // Prefill outputs from the last published remote content
    // so agents can see and update existing content in incremental mode.
    // Must happen AFTER saveBundleState so the hash update persists.
    const publishedSummary = extractMarkedSummary(target.description ?? '');
    if (publishedSummary) {
      await this.workspace.prefillOutputIfEmpty('summary.md', publishedSummary);
    }
    // review.md is never prefilled — it is the current publish body only

    return {
      bundle,
      bundleState,
      contextPath,
      mode,
      targetCodeChanged,
      threadsChanged,
      descriptionChanged,
      hasCheckpoint: remoteCheckpoint !== null,
      prunedReplies,
      publishedActionCount: previousActions.length,
      diffFallback: diffFallback
        ? {
            provider: diffFallback.provider,
            reason: diffFallback.reason,
            incompleteFileCount: diffFallback.incompleteFileCount,
            baseSha: diffFallback.baseSha,
            headSha: diffFallback.headSha,
          }
        : undefined,
    };
  }

  /**
   * Open: resolve ref, fetch snapshot.
   */
  async open(ref?: string, defaultRepo?: string): Promise<ReviewTarget> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    return this.provider.getTargetSnapshot(targetRef);
  }

  /**
   * Check if the current git branch matches the active bundle's target.
   * Returns null if no bundle or no git info available.
   */
  async checkBranchMismatch(): Promise<{ currentBranch: string; expectedBranch: string; targetId: string } | null> {
    const bundleState = await this.workspace.loadBundleState();
    if (!bundleState) return null;
    try {
      const currentBranch = await this.git.currentBranch();
      if (!currentBranch || currentBranch === 'HEAD') return null;
      if (currentBranch !== bundleState.target.sourceBranch) {
        return {
          currentBranch,
          expectedBranch: bundleState.target.sourceBranch,
          targetId: bundleState.target.id,
        };
      }
    } catch {
      // Can't check — not a git repo or API error
    }
    return null;
  }

  /**
   * Checkout: fetch the MR source branch and switch to it.
   * If we're not inside a git repo, performs a shallow clone instead.
   */
  async checkout(ref: string, defaultRepo?: string): Promise<CheckoutResult> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    const target = await this.provider.getTargetSnapshot(targetRef);

    const inRepo = await this.git.isGitRepo();

    // Some providers (GitHub) expose a permanent refspec for each PR that works even
    // after the source branch is deleted from the contributor's fork.
    const sourceRefspec = this.provider.getSourceRefspec?.(targetRef);

    if (!inRepo) {
      // No git repo — shallow clone into a sub-directory, similar to `git clone`.
      const baseCloneUrl = this.provider.getCloneUrl(targetRef.repository);
      let clonedDir: string;

      if (sourceRefspec) {
        // Refspec-based clone: fetch via the permanent PR ref from the base repo.
        // Reliable even when the source branch has been deleted from the contributor's fork.
        clonedDir = await GitHelper.cloneAndCheckoutRef(baseCloneUrl, sourceRefspec, target.sourceBranch, this.git.cwd);
      } else {
        // Fallback: clone from fork (if fork PR) or base repo using the branch name.
        const checkoutRepo = target.headRepository ?? targetRef.repository;
        const cloneUrl = this.provider.getCloneUrl(checkoutRepo);
        clonedDir = await GitHelper.clone(cloneUrl, target.sourceBranch, this.git.cwd);
      }

      return { branch: target.sourceBranch, target, clonedTo: clonedDir };
    }

    // Existing repo — fetch the source branch.
    if (sourceRefspec) {
      // Fetch the PR ref from origin and create a local branch for it.
      // This works for both same-repo and fork PRs, even after branch deletion.
      await this.git.fetchRef('origin', sourceRefspec, target.sourceBranch);
    } else if (target.headRepository) {
      // No permanent refspec support — fetch directly from the fork URL.
      const forkCloneUrl = this.provider.getCloneUrl(target.headRepository);
      await this.git.fetchBranchFromUrl(forkCloneUrl, target.sourceBranch);
    } else {
      await this.git.fetchBranch(target.sourceBranch);
    }

    try {
      // Let Git decide whether switching is safe.
      //
      // This allows harmless local state, such as unrelated untracked files,
      // while still refusing switches that would overwrite local changes.
      await this.git.switchBranch(target.sourceBranch);
    } catch (error) {
      throw new Error(
        [
          `Could not switch to branch '${target.sourceBranch}'.`,
          '',
          `Original error: ${error instanceof Error ? error.message : String(error)}`,
        ].join('\n'),
        { cause: error },
      );
    }

    return { branch: target.sourceBranch, target };
  }

  // ─── Write operations (guarded) ─────────────────────────

  async publishReply(ref?: string, threadId?: string, body?: string, defaultRepo?: string): Promise<void> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    if (!threadId) throw new Error('threadId is required');
    if (!body) throw new Error('reply body is required');
    const resolvedId = await this.workspace.resolveThreadRef(threadId);
    const markedBody = `${ReviewOrchestrator.COMMENT_MARKER}\n${body}${ReviewOrchestrator.AI_FOOTER}`;
    await this.provider.postReply(targetRef, resolvedId, markedBody);
  }

  async resolveThread(ref?: string, threadId?: string, defaultRepo?: string): Promise<void> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    if (!threadId) throw new Error('threadId is required');
    const resolvedId = await this.workspace.resolveThreadRef(threadId);
    await this.provider.resolveThread(targetRef, resolvedId);
  }

  async updateDescription(ref?: string, body?: string, defaultRepo?: string): Promise<void> {
    const targetRef = await this.resolveRef(ref, defaultRepo);
    if (!body) throw new Error('description body is required');
    await this.provider.updateDescription(targetRef, body);
  }

  /**
   * Publish a new finding as a discussion thread on the MR/PR.
   * Returns the created thread ID.
   */
  async publishFinding(finding: NewFinding, defaultRepo?: string): Promise<string> {
    const targetRef = await this.resolveRef(undefined, defaultRepo);
    const markedBody = `${ReviewOrchestrator.COMMENT_MARKER}\n${finding.body}${ReviewOrchestrator.AI_FOOTER}`;
    return this.provider.createThread(targetRef, markedBody, {
      oldPath: finding.oldPath,
      newPath: finding.newPath,
      newLine: finding.newLine,
      oldLine: finding.oldLine,
    });
  }

  /** Resolve a T-NNN shorthand to the full thread SHA. */
  async resolveThreadRef(ref: string): Promise<string> {
    return this.workspace.resolveThreadRef(ref);
  }

  /**
   * Publish review: advance the checkpoint via the description state block,
   * and optionally publish review.md as a visible comment/note.
   *
   * - Hidden state is always written to the MR/PR description/body.
   * - If visibleContent is non-empty, publishes it as a new normal comment/note.
   * - If visibleContent is empty, no visible review artifact is created.
   */
  async publishReview(visibleContent: string, defaultRepo?: string): Promise<{ created: boolean; noteId?: string }> {
    await this.advanceCheckpoint(defaultRepo);

    // Publish visible review body if non-empty
    if (visibleContent.trim()) {
      const targetRef = await this.resolveRef(undefined, defaultRepo);
      const markedBody = `${REVIEW_NOTE_MARKER}\n${visibleContent.trim()}${REVIEW_NOTE_FOOTER}`;
      const noteId = await this.provider.createNote(targetRef, markedBody);
      return { created: true, noteId };
    }

    return { created: false };
  }

  /**
   * Publish review as part of a GitHub PR review batch (with findings as inline comments).
   * Advances the checkpoint via the description state block.
   */
  async publishReviewBatch(
    findings: NewFinding[],
    reviewBody: string,
    defaultRepo?: string,
  ): Promise<{ created: boolean; noteId?: string }> {
    // Build provider comment objects — marker + footer added here, same as publishFinding
    const comments = findings.map((f) => {
      const side: 'LEFT' | 'RIGHT' = f.oldLine != null && f.newLine == null ? 'LEFT' : 'RIGHT';
      return {
        body: `${ReviewOrchestrator.COMMENT_MARKER}\n${f.body}${ReviewOrchestrator.AI_FOOTER}`,
        path: side === 'LEFT' ? f.oldPath : f.newPath,
        line: side === 'LEFT' ? f.oldLine : f.newLine,
        side,
      };
    });

    // Submit the PR review batch
    if (this.provider.submitReview) {
      const targetRef = await this.resolveRef(undefined, defaultRepo);
      const body = reviewBody.trim() ? `${reviewBody.trim()}${REVIEW_NOTE_FOOTER}` : '';
      await this.provider.submitReview(targetRef, comments, body, 'COMMENT');
    }

    await this.advanceCheckpoint(defaultRepo);

    return { created: findings.length > 0 || !!reviewBody.trim() };
  }

  /**
   * Snapshot current MR/PR state and write the checkpoint into the description body.
   */
  private async advanceCheckpoint(defaultRepo?: string): Promise<void> {
    const targetRef = await this.resolveRef(undefined, defaultRepo);

    const [target, rawThreads] = await Promise.all([
      this.provider.getTargetSnapshot(targetRef),
      this.provider.listAllThreads(targetRef),
    ]);

    // Identify existing review note for thread filtering
    let reviewNoteId: string | null = null;
    try {
      const existingNote = await this.provider.findNoteByMarker(targetRef, REVIEW_NOTE_MARKER);
      if (existingNote) reviewNoteId = existingNote.id;
    } catch {
      // Provider lookup failed
    }

    const allThreads = filterReviewThreads(rawThreads, reviewNoteId);
    const currentThreadsDigest = computeAggregateThreadsDigest(allThreads);
    const currentDescriptionDigest = computeContentHash(sanitizeDescriptionForAgent(target.description ?? ''));
    const threadDigests = computeThreadDigestMap(allThreads);

    const versions = await this.provider.getDiffVersions(targetRef);
    const latestVersionId = versions.length > 0 ? versions[0].versionId : undefined;

    const checkpointState = buildCheckpointState(
      targetRef,
      target.diffRefs.headSha,
      target.diffRefs.baseSha,
      target.diffRefs.startSha,
      currentThreadsDigest,
      latestVersionId,
      currentDescriptionDigest,
      threadDigests,
    );

    const patchedDescription = patchDescriptionWithState(target.description ?? '', checkpointState);
    await this.provider.updateDescription(targetRef, patchedDescription);
  }

  // ─── Helpers ────────────────────────────────────────────

  private async resolveRef(ref?: string, defaultRepo?: string): Promise<ReviewTargetRef> {
    // 1. Explicit ref
    if (ref) {
      const targetRef = this.provider.resolveTarget(ref);
      if (!targetRef.repository && defaultRepo) {
        targetRef.repository = defaultRepo;
      }
      if (!targetRef.repository) {
        targetRef.repository = await this.git.deriveRepoSlug();
      }
      return targetRef;
    }

    // 2. Existing bundle.json
    const bundleState = await this.workspace.loadBundleState();
    if (bundleState) {
      // If we can determine the current branch, check it matches
      try {
        const currentBranch = await this.git.currentBranch();
        if (currentBranch && currentBranch !== 'HEAD' && currentBranch !== bundleState.target.sourceBranch) {
          throw new Error(
            `Branch mismatch: current branch "${currentBranch}" does not match ` +
              `the bundle's MR source branch "${bundleState.target.sourceBranch}" (!${bundleState.target.id}).\n` +
              `Run \`revkit clean\` to remove the stale bundle, or switch to "${bundleState.target.sourceBranch}".`,
          );
        }
      } catch (err) {
        if (err instanceof Error && err.message.includes('Branch mismatch')) throw err;
      }
      return {
        provider: bundleState.target.provider,
        repository: bundleState.target.repository,
        targetType: bundleState.target.type,
        targetId: bundleState.target.id,
      };
    }

    // 3. Auto-detect MR from current git branch
    let repo = defaultRepo;
    if (!repo) {
      try {
        repo = await this.git.deriveRepoSlug();
      } catch {
        /* not a git repo */
      }
    }
    if (repo) {
      try {
        const branch = await this.git.currentBranch();
        if (branch && branch !== 'HEAD') {
          const targets = await this.provider.findTargetByBranch(repo, branch);
          if (targets.length === 1) {
            return targets[0];
          }
          if (targets.length > 1) {
            const ids = targets.map((t) => `!${t.targetId}`).join(', ');
            throw new Error(
              `Multiple open MRs found for branch "${branch}": ${ids}\n` +
                'Specify one explicitly: `revkit prepare !<id>`',
            );
          }
        }
      } catch (err) {
        if (err instanceof Error && err.message.includes('Multiple open MRs')) throw err;
      }
    }

    throw new Error(
      'Could not determine which MR to prepare.\n' +
        'No ref provided, no existing bundle, and no open MR found for the current branch.\n' +
        'Run `revkit prepare !<id>` to specify one explicitly.',
    );
  }

  private async maybeRegenerateGitLabPatch(
    target: ReviewTarget,
    diffs: ReviewDiff[],
  ): Promise<LocalPatchFallbackResult | undefined> {
    if (target.provider !== 'gitlab') return undefined;

    const incompleteDiffs = diffs.filter((d) => {
      const missingModifiedDiff = !d.diff && !d.newFile && !d.deletedFile;
      return d.incomplete || missingModifiedDiff;
    });
    const changesCountOverflow = target.changesCount?.trim().endsWith('+') === true;

    if (incompleteDiffs.length === 0 && !changesCountOverflow) return undefined;

    const baseSha = target.diffRefs.baseSha;
    const headSha = target.diffRefs.headSha;
    const reasonParts = [
      ...new Set(incompleteDiffs.map((d) => d.incompleteReason ?? 'missing_diff')),
      ...(changesCountOverflow ? [`changes_count=${target.changesCount}`] : []),
    ];
    const reason = reasonParts.join(', ');

    if (!baseSha || !headSha) {
      throw this.gitLabLocalPatchFailure(baseSha, headSha, 'MR diff_refs.base_sha or diff_refs.head_sha is missing.');
    }

    try {
      await this.ensureCommitsAvailableForDiff(target, baseSha, headSha);
      const patchContent = await this.git.diffForReview(baseSha, headSha);
      return {
        provider: 'gitlab',
        reason,
        incompleteFileCount: incompleteDiffs.length,
        baseSha,
        headSha,
        patchContent,
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      throw this.gitLabLocalPatchFailure(baseSha, headSha, message);
    }
  }

  private async ensureCommitsAvailableForDiff(target: ReviewTarget, baseSha: string, headSha: string): Promise<void> {
    let missing = await this.missingCommits(baseSha, headSha);
    if (missing.length === 0) return;

    const fetchErrors: string[] = [];

    for (const sha of missing) {
      try {
        await this.git.fetchCommit(sha);
      } catch (err) {
        fetchErrors.push(`git fetch origin ${sha}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    try {
      await this.git.fetch();
    } catch (err) {
      fetchErrors.push(`git fetch origin: ${err instanceof Error ? err.message : String(err)}`);
    }

    for (const branch of [target.targetBranch, target.sourceBranch]) {
      if (!branch) continue;
      try {
        await this.git.fetchBranch(branch);
      } catch (err) {
        fetchErrors.push(`git fetch origin ${branch}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    missing = await this.missingCommits(baseSha, headSha);
    if (missing.length > 0) {
      const details =
        fetchErrors.length > 0 ? `\n\nFetch attempts:\n${fetchErrors.map((e) => `  ${e}`).join('\n')}` : '';
      throw new Error(`Required commit(s) not available locally: ${missing.join(', ')}.${details}`);
    }
  }

  private async missingCommits(baseSha: string, headSha: string): Promise<string[]> {
    const checks = await Promise.all([
      this.git.hasCommit(baseSha).then((ok) => (ok ? null : baseSha)),
      this.git.hasCommit(headSha).then((ok) => (ok ? null : headSha)),
    ]);
    return checks.filter((sha): sha is string => sha !== null);
  }

  private reviewDiffsFromPatch(patchContent: string): ReviewDiff[] {
    const lineMap = parsePatch(patchContent);
    const patchSections = WorkspaceManager.splitPatchByFile(patchContent);

    return lineMap.files.map((file, index) => ({
      oldPath: file.oldPath,
      newPath: file.newPath,
      diff: this.stripGitDiffHeader(patchSections[index] ?? ''),
      newFile: file.status === 'added',
      renamedFile: file.status === 'renamed',
      deletedFile: file.status === 'deleted',
    }));
  }

  private stripGitDiffHeader(patchSection: string): string {
    const lines = patchSection.split('\n');
    const diffStart = lines.findIndex(
      (line) => line.startsWith('--- ') || line.startsWith('@@ ') || line.startsWith('Binary files '),
    );
    return diffStart >= 0 ? lines.slice(diffStart).join('\n') : '';
  }

  private gitLabLocalPatchFailure(baseSha: string, headSha: string, reason: string): Error {
    return new Error(
      `GitLab returned incomplete MR diff data, and revkit could not regenerate the patch from local Git.\n\n` +
        `Required range:\n` +
        `  base: ${baseSha || '<missing>'}\n` +
        `  head: ${headSha || '<missing>'}\n\n` +
        `Reason:\n` +
        `  ${reason.replace(/\n/g, '\n  ')}\n\n` +
        `The prepared review bundle would be incomplete, so prepare was aborted.`,
    );
  }
}
