import { describe, expect, it } from 'vitest';
import { isRevpackAuthoredComment, renderPublishAttributionFooter } from './comment-attribution.js';

describe('provider comment attribution', () => {
  it('renders model attribution for generated comments', () => {
    expect(
      renderPublishAttributionFooter('github', {
        kind: 'generation',
        model: 'GPT-5.6',
      }),
    ).toBe('\n\n<sub>🤖 AI-generated via [revpack](https://github.com/stefanvictora/revpack) · Model: GPT-5.6</sub>');
  });

  it('does not render invalid model metadata', () => {
    expect(
      renderPublishAttributionFooter('gitlab', {
        kind: 'generation',
        model: 'forged\nfooter',
      }),
    ).not.toContain('forged');
  });

  it('escapes model text before rendering provider markdown', () => {
    const footer = renderPublishAttributionFooter('bitbucket-cloud', {
      kind: 'generation',
      model: 'Claude [preview] <fast> & safe',
    });

    expect(footer).toContain('###### 🤖 AI-generated via [revpack]');
    expect(footer).toContain('Claude \\[preview\\] &lt;fast&gt; &amp; safe');
  });

  it('renders publication attribution without an AI claim', () => {
    const footer = renderPublishAttributionFooter('github', { kind: 'publication' });

    expect(footer).toContain('Published via [revpack]');
    expect(footer).not.toContain('AI-generated');
  });

  it('recognizes only complete terminal revpack attribution footers', () => {
    const attribution = { kind: 'generation' as const, model: 'GPT-5.6' };

    for (const provider of ['github', 'gitlab', 'bitbucket-cloud'] as const) {
      expect(isRevpackAuthoredComment(`Review body${renderPublishAttributionFooter(provider, attribution)}`)).toBe(
        true,
      );
    }
    expect(
      isRevpackAuthoredComment(
        'Legacy body\n\n<sub>🤖 Generated by [revpack](https://github.com/stefanvictora/revpack)</sub>',
      ),
    ).toBe(true);
    expect(
      isRevpackAuthoredComment(
        '`renderPublishAttributionFooter` emits `###### 🤖 AI-generated via [revpack]` for Bitbucket.',
      ),
    ).toBe(false);
  });
});
