import type { ProviderType, PublishAttribution } from '../core/types.js';
import { normalizeGenerationModel } from '../core/generation-attribution.js';

const REVPK_LINK = '[revpack](https://github.com/stefanvictora/revpack)';
const REVPACK_LINK_PATTERN = String.raw`\[revpack\]\(https://github\.com/stefanvictora/revpack\)`;
const ATTRIBUTION_CONTENT_PATTERN = String.raw`(?:🤖 AI-generated via ${REVPACK_LINK_PATTERN}(?: · Model: [^\r\n<]+)?|Published via ${REVPACK_LINK_PATTERN}|🤖 Generated by ${REVPACK_LINK_PATTERN})`;
const REVPACK_ATTRIBUTION_FOOTER_PATTERN = new RegExp(
  String.raw`(?:^|\r?\n)(?:<sub>${ATTRIBUTION_CONTENT_PATTERN}</sub>|###### ${ATTRIBUTION_CONTENT_PATTERN})[ \t]*(?:\r?\n[ \t]*)*$`,
  'u',
);

export function renderPublishAttributionFooter(provider: ProviderType, attribution: PublishAttribution): string {
  const model = attribution.kind === 'generation' ? normalizeGenerationModel(attribution.model) : undefined;
  const prefix = attribution.kind === 'generation' ? '🤖 AI-generated via' : 'Published via';
  const modelSuffix = model ? ` · Model: ${escapeAttributionText(model)}` : '';
  const content = `${prefix} ${REVPK_LINK}${modelSuffix}`;
  return provider === 'bitbucket-cloud' ? `\n\n###### ${content}` : `\n\n<sub>${content}</sub>`;
}

export function isRevpackAuthoredComment(body: string): boolean {
  return body.startsWith('<!-- revpack') || REVPACK_ATTRIBUTION_FOOTER_PATTERN.test(body);
}

function escapeAttributionText(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/([\\`*_[\]()])/g, '\\$1');
}
