import type { ReviewTargetRef } from '../core/types.js';
import { MARKER_START, MARKER_END } from './description-summary.js';

// ─── Checkpoint types ────────────────────────────────────

export interface CheckpointState {
  schemaVersion: number;
  tool: { name: string; version: string };
  target: {
    provider: string;
    repository: string;
    type: string;
    id: string;
  };
  checkpoint: {
    createdAt: string;
    headSha: string;
    baseSha: string;
    startSha: string;
    providerVersionId?: string;
    threadsDigest: string | null;
    descriptionDigest?: string | null;
    /** Per-thread digests at checkpoint time, keyed by provider thread ID. */
    threadDigests: Record<string, string>;
  };
}

export interface ParsedCheckpoint {
  state: CheckpointState;
  visibleContent: string;
}

// ─── Constants ───────────────────────────────────────────

export const CHECKPOINT_MARKER_START = '<!-- revpack:state';
export const CHECKPOINT_MARKER_END = '-->';
export const CHECKPOINT_STATE_BLOCK_REGEX = /<!-- revpack:state[\s\S]*?-->/g;

export const REVIEW_NOTE_MARKER = '<!-- revpack:review-note -->';
export const REVIEW_NOTE_FOOTER = '\n\n<sub>🤖 Generated by [revpack](https://github.com/stefanvictora/revpack)</sub>';

/**
 * Strip the AI-generated footer from review note visible content (for prefill round-trips).
 */
export function stripReviewNoteFooter(content: string): string {
  return content.replace(REVIEW_NOTE_FOOTER.trimStart(), '').trimEnd();
}

// ─── Parser ──────────────────────────────────────────────

/**
 * Decode and validate an encoded checkpoint state string (base64url or raw JSON).
 * Returns the validated CheckpointState or null if decoding/validation fails.
 */
function decodeAndValidateState(encoded: string): CheckpointState | null {
  if (!encoded) return null;

  let state: CheckpointState;
  try {
    const decoded = Buffer.from(encoded, 'base64url').toString('utf-8');
    state = JSON.parse(decoded) as CheckpointState;
  } catch {
    try {
      state = JSON.parse(encoded) as CheckpointState;
    } catch {
      return null;
    }
  }

  if (!state || typeof state !== 'object') return null;
  if (!state.checkpoint || typeof state.checkpoint.headSha !== 'string') return null;
  state.checkpoint.threadDigests ??= {};

  return state;
}

// ─── Serializer ──────────────────────────────────────────

/**
 * Build a CheckpointState from the current review context.
 */
export function buildCheckpointState(
  targetRef: ReviewTargetRef,
  headSha: string,
  baseSha: string,
  startSha: string,
  threadsDigest: string | null,
  providerVersionId?: string,
  descriptionDigest?: string | null,
  threadDigests?: Record<string, string>,
): CheckpointState {
  return {
    schemaVersion: 1,
    tool: { name: 'revpack', version: '0.2.0' },
    target: {
      provider: targetRef.provider,
      repository: targetRef.repository,
      type: targetRef.targetType,
      id: targetRef.targetId,
    },
    checkpoint: {
      createdAt: new Date().toISOString(),
      headSha,
      baseSha,
      startSha,
      providerVersionId,
      threadsDigest,
      descriptionDigest: descriptionDigest ?? null,
      threadDigests: threadDigests ?? {},
    },
  };
}

/**
 * Encode a CheckpointState as a base64url JSON string for embedding in HTML comments.
 */
export function encodeCheckpointState(state: CheckpointState): string {
  const json = JSON.stringify(state);
  return Buffer.from(json, 'utf-8').toString('base64url');
}

// ─── Description-body state block functions ──────────────

/**
 * Parse the hidden revpack:state block from an MR/PR description/body.
 * Returns the decoded CheckpointState or null if no block found.
 * Throws if multiple state blocks are found (requires manual repair).
 */
export function parseDescriptionState(description: string): CheckpointState | null {
  const matches = [...description.matchAll(CHECKPOINT_STATE_BLOCK_REGEX)];

  if (matches.length === 0) return null;

  if (matches.length > 1) {
    throw new Error(
      'Found multiple revpack state blocks in the PR/MR description. Remove the stale duplicate block and rerun the command.',
    );
  }

  const block = matches[0][0];
  const afterStart = block.indexOf(CHECKPOINT_MARKER_START) + CHECKPOINT_MARKER_START.length;
  const endIdx = block.indexOf(CHECKPOINT_MARKER_END, afterStart);
  if (endIdx === -1) return null;

  const encoded = block.slice(afterStart, endIdx).trim();
  return decodeAndValidateState(encoded);
}

/**
 * Build the hidden state block string for embedding in an MR/PR description.
 */
export function buildDescriptionStateBlock(state: CheckpointState): string {
  const encoded = encodeCheckpointState(state);
  return `${CHECKPOINT_MARKER_START}\n${encoded}\n${CHECKPOINT_MARKER_END}`;
}

/**
 * Patch an MR/PR description to insert or replace the hidden state block.
 * - If a state block already exists, replaces it in place.
 * - If no state block exists, appends it at the bottom.
 * Preserves all other content.
 */
export function patchDescriptionWithState(description: string, state: CheckpointState): string {
  const stateBlock = buildDescriptionStateBlock(state);
  const matches = [...description.matchAll(CHECKPOINT_STATE_BLOCK_REGEX)];

  if (matches.length > 1) {
    throw new Error(
      'Found multiple revpack state blocks in the PR/MR description. Remove the stale duplicate block and rerun the command.',
    );
  }

  if (matches.length === 1) {
    // Replace existing block in place
    return description.replace(CHECKPOINT_STATE_BLOCK_REGEX, stateBlock);
  }

  // Append at the bottom
  const separator = description.trimEnd() ? '\n\n' : '';
  return description.trimEnd() + separator + stateBlock;
}

/**
 * Strip the hidden revpack state block and the revpack-generated summary section
 * from a description, returning only the original human-written content.
 */
export function sanitizeDescriptionForAgent(description: string): string {
  // Strip the hidden state block first.
  let result = description.replace(CHECKPOINT_STATE_BLOCK_REGEX, '');

  // Strip the revpack-generated summary section (<!-- revpack:start --> ... <!-- revpack:end -->),
  // including the preceding horizontal-rule separator that mergeWithMarkers adds.
  const startIdx = result.indexOf(MARKER_START);
  if (startIdx !== -1) {
    const endIdx = result.indexOf(MARKER_END, startIdx + MARKER_START.length);
    if (endIdx !== -1) {
      const before = result.slice(0, startIdx);
      const after = result.slice(endIdx + MARKER_END.length);
      // Remove the "\n\n---\n\n" separator that mergeWithMarkers prepends when appending.
      const trimmedBefore = before.replace(/\n\n---\n\n$/, '');
      result = trimmedBefore + after;
    }
  }

  return result.trimEnd();
}
