export const GENERATION_MODEL_MAX_LENGTH = 80;

const REVPACK_LINK_PATTERN = String.raw`\[revpack\]\(https://github\.com/stefanvictora/revpack\)`;
const ATTRIBUTION_CONTENT_PATTERN = String.raw`(?:🤖 AI-generated via ${REVPACK_LINK_PATTERN}(?: · Model: [^\r\n<]+)?|Published via ${REVPACK_LINK_PATTERN}|🤖 Generated by ${REVPACK_LINK_PATTERN})`;
const REVPACK_ATTRIBUTION_FOOTER_PATTERN = new RegExp(
  String.raw`(?:^|\r?\n)(?:<sub>${ATTRIBUTION_CONTENT_PATTERN}</sub>|###### ${ATTRIBUTION_CONTENT_PATTERN})[ \t]*(?:\r?\n[ \t]*)*$`,
  'u',
);

/**
 * Normalize an agent-reported model label for display.
 * Invalid labels are ignored so attribution metadata never blocks publication.
 */
export function normalizeGenerationModel(value: unknown): string | undefined {
  if (typeof value !== 'string' || /[\p{Cc}\p{Cf}]/u.test(value)) return undefined;
  const normalized = value.replace(/\s+/g, ' ').trim();
  if (!normalized || normalized.length > GENERATION_MODEL_MAX_LENGTH) return undefined;
  return normalized;
}

export function isRevpackAuthoredComment(body: string): boolean {
  return body.startsWith('<!-- revpack') || REVPACK_ATTRIBUTION_FOOTER_PATTERN.test(body);
}
